name: opengl
description: OpenGL FFI bindings
version: 0.1.0
author: root ext <root.ext@gmail.com>
homepage: https://gitlab.com/ext/dart-opengl

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
