name: opengl
description: OpenGL 4.6 FFI bindings for Dart. Supports Linux, macOS and Windows.
version: 1.0.0
author: root ext <root.ext@gmail.com>
homepage: https://gitlab.com/ext/dart-opengl

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: 1.0.0
