name: opengl
description: OpenGL 4.6 FFI bindings for Dart. Supports Windows and Linux desktops.
version: 0.1.0+1
author: root ext <root.ext@gmail.com>
homepage: https://gitlab.com/ext/dart-opengl

environment:
  sdk: '>=2.3.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
